version: '3.9'
services:
  db:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./cache_data:/var/lib/cache_data

volumes:
  data:
  cache_data:

